### ISSUE TITLE
Color transitions take time to render

### ISSUE THREAD

**Issue by pratapvardhan** [gramener/comicgen#110]
Think, the color render is going through all the intermediate pseudo-selections. Probably throttle the event call?

https://user-images.githubusercontent.com/3757165/113705391-ff0d8a80-96fa-11eb-9c38-a2f525134a5f.mp4

cc @ShamiliRobbi-27 @sanand0

**Comment by sanand0** [comment]
Agreed. Good idea. Thanks @pratapvardhan
