### ISSUE TITLE
additional feature that can be added !

### ISSUE THREAD

**Issue by TarunBilluri** [gramener/comicgen#111]
For speech bubble feature, 
along with pointerx &  pointery, can we add a position(left-right-top-bottom) to select the side on which our pointer is added to the boundary ?

**Comment by sanand0** [comment]
@TarunBilluri by setting pointerx/pointery to negative values, you can move it to any side. For example:

https://gramener.com/comicgen/v1/#name=speechbubble&pointerx=-30

Does this work for you?

**Comment by TarunBilluri** [comment]
Hi @sanand0 , thanks for the reply. Yes I could use the negative values to move to other sides. My idea intends to quickly move to the required side without playing around the  numbers.

**Comment by sanand0** [comment]
Got you @TarunBilluri. We do plan to build a UI that allows us to move the pointer. This will be a part of that. Until then, will close this issue. Thanks!
