### ISSUE TITLE
Parameterization of colors 

### ISSUE THREAD

**Issue by RamyaMylavarapu** [gramener/comicgen#61]
- [ ]   Test color class for Ava, Evan & Bean (@tejesh95 to test)
- [ ]   Convert Ava, Evan & Bean into classes for color (@tejesh95 to test)
- [ ]   Test color face for Dee (@sanand0 to test)

**Comment by RamyaMylavarapu** [comment]
- Exported Ava,Evan & Bean files via illustrator. Now we can see the color classes. 
- Added Bean's face. Right now it is white, we can change the color. Here are the files https://cloud.gramener.com/d/1594e7d4193a40c38890/
<img width="344" alt="Screen Shot 2020-02-04 at 12 38 54 PM" src="https://user-images.githubusercontent.com/58559516/73721976-763c3d00-474b-11ea-8357-39a5e50fef8a.png">

**Comment by sanand0** [comment]
Cool. @tejesh95 is this fine for you? If yes, we can move on to Dee. @RamyaMylavarapu I can test Dee.

**Comment by tejesh0** [comment]
Examples: [Evan AngryFrustrated](https://cloud.gramener.com/d/1594e7d4193a40c38890/files/?p=%2Fevan%20%26%20ava%2Fava%2Fangryfrustrated.svg) and [Ava AngryFrustrated](https://cloud.gramener.com/d/1594e7d4193a40c38890/files/?p=%2Fevan%20%26%20ava%2Fevan%2Fangryfrustrated.svg) does not have classes and still use fill attributes.

For time being, let's suppose classes are generated from Illustrator correctly. 

Even if so, there is an edge case to be handled. Body svg of Evan will have a class `.st1 { fill: 'brown'}` but autogenerated class name from Illustrator for Face svg of Evan can contain the same classname assigned in `<svg><style>.st1 {fill: 'darkbrown'} </style> </svg>`

Two different SVGs having same class names loaded in same page will override one of them.

**Comment by RamyaMylavarapu** [comment]
Anand, I exported two Dee's emotions. Pls let me know which works better. https://cloud.gramener.com/d/9dc55360b6d749309b1f/

**Comment by sanand0** [comment]
Here are anomalies I see. I just randomly changed the class colors and this is the result. Here is the SVG: [deeface1.zip](https://github.com/gramener/comicgen/files/4178805/deeface1.zip)

![image](https://user-images.githubusercontent.com/63734/74118572-06620280-4be2-11ea-9200-00303b3a68b3.png)

@RamyaMylavarapu please revise the images to ensure that there's one color each for:
the face fill, the face outline, the hair, and the shadows. I don't think we need more colors.

@tejesh95 We can parametrize just the face fill and the hair.

**Comment by sanand0** [comment]
Same problems with [deeface2.zip](https://github.com/gramener/comicgen/files/4178816/deeface2.zip):

![image](https://user-images.githubusercontent.com/63734/74118804-f696ee00-4be2-11ea-8b5d-bc0ea4e13ad1.png)

**Comment by sanand0** [comment]
Done with Comicgen v1
