### ISSUE TITLE
Document how designers can create new Continuous Characters 

### ISSUE THREAD

**Issue by tejesh0** [gramener/comicgen#70]
(things to keep in mind when creating the characters)

- [ ] Name all layers of character. ensure the name doesn't start with numbers/special characters. (Because the names are translated as id attribute for svg elements
- [ ] For better performance of interpolation, ensure number of vector points are same.

**Comment by tejesh0** [comment]
- [ ] Character must not have transparent background. 
- [ ] Minimal vector points - need to identify design tools and illustration methods that export with minimal vector points.

**Comment by tejesh0** [comment]
@RamyaMylavarapu

**Comment by sanand0** [comment]
Closed via bc86667
