### ISSUE TITLE
The example for the "emotion slider" feature displays the wrong image

### ISSUE THREAD

**Issue by richielionell** [gramener/comicgen#72]
The example for the "[emotion slider](https://gramener.com/comicgen/#api)" feature needs to show "zoozoo" but shows the image of "Dee".

![image](https://user-images.githubusercontent.com/4058058/79209400-ff18d880-7e60-11ea-8271-f5f3f5e4d05b.png)

**Comment by tejesh0** [comment]
bc866676d800d5dbd87b7f97d6d1a01e012b3cdf fixes this
