### ISSUE TITLE
'Save' as parameter in url

### ISSUE THREAD

**Issue by richielionell** [gramener/comicgen#80]
Would be useful to save the image through a URL call. This makes it easier to import the image in Excel, Google Docs, PPT etc. 

For example;

` https://gramener.com/comicgen/#?name=dee&emotion=angry&pose=handsinpocket&ext=svg&mirror=&x=0&y=0&scale=1&width=500&height=600&save=png`

**Comment by sanand0** [comment]
Resolved in Comicgen v1 via ?ext=png
