### ISSUE TITLE
Character's hair missed when svg image copied to powerpoint

### ISSUE THREAD

**Issue by rajeshp7** [gramener/comicgen#89]
I downloaded the svg image of Priya's character and pasted it to powerpoint. Head portion of the character is missing.
Please find the attachments for your reference.
![image](https://user-images.githubusercontent.com/47620400/91793304-6deea680-ec35-11ea-915a-2c17d2276779.png)

**Comment by tejesh0** [comment]
@rajeshp7 could you please verify if these updated files are rendered properly in your powerpoint version?

https://raw.githubusercontent.com/gramener/comicgen/26bfaa2e14fe874dbddc604965ac221feaa4fb8a/svg/priya/straight/emotion/neutral.svg

https://raw.githubusercontent.com/gramener/comicgen/26bfaa2e14fe874dbddc604965ac221feaa4fb8a/svg/priyanuova/straight/emotion/neutral.svg

**Comment by sanand0** [comment]
@tejesh0 What exactly prevented PowerPoint from displaying these? Is it mask layers in general? Or specific types of masks?

Basically, is there something Ramya should avoid?

**Comment by sanand0** [comment]
Resolved in Comicgen v1
